### ISSUE TITLE
[Paladin] Judgements are wrongly limited to one per paladin (instead of one per target)

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#129]
**Description:**
Paladin's Judgements (Judgement of Light, Judgement of Wisdom, etc.) are supposed to be restricted to   
1 judgement per paladin per target. That means that you should be able to have multiple Judgements up on multiple different targets (for example Light/Light/Wisdom on 3 different mobs.) Currently you can only have one Judgement at a time.

Quoting a bug report by Ayv:

During the entirety of The Burning Crusade expansion, a single Paladin was able to keep multiple targets judged at any given time, only being limited by one type of Judgement debuff (those being Crusader/Justice/Light/Wisdom) per target, per Paladin. And by the Paladins actions to keep refreshing the active Judgements with his/her autoswings, and/or using the ability Crusader Strike.

Maintankadin removed its old forum posts and Wayback was also unable to retreive it due to its age. However here is a screenshot of the post from 2007.
http://i.imgur.com/Hyqigza.png
And here is a wowhead post from 2008.
http://www.wowhead.com/quest=7647/judgment-and-redemption#comments:id=341793

The Problem:
A single Paladin can only debuff Judge one target currently.

How it should work:
A single Paladin should be able to debuff Judge any combination of mobs with any combination of judgement debuffs. limited to 1 debuff type per mob, per paladin.

How to reproduce:
Create a Paladin and multiple mobs.
Judge either Crusader/Justice/Light/Wisdom on the first mob, followed by Judging it on a second mob. Both Judgement debuffs should persist.

**Comment by kelno** [comment]
Fixed!

**Comment by Jerrythemagicdog** [comment]
Still the same behavior in TLK:

https://www.warcraftmovies.com/movieview.php?id=164185
https://www.youtube.com/watch?v=-EqsWWzGRb8

3:46 - Hofferand casts Judgement on Omx
3:54 - Hofferand casts Judgement on Deadlyintent
Judgement on Omx persists.
