### ISSUE TITLE
[Hunter] Delay between shots

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1523]
**Bug description**
There are unusual delays after Auto-Shot and GCD.
_yellow = steady
green = auto (red = 0.5 cast)
black = global
cyan = arcane
purple = multi_
[2.7 weapon 15% haste](https://postimg.cc/fkc3LMdN)
[2.8 weapon 15% haste](https://postimg.cc/7fq5Jj1T)
[2.9 weapon 15% haste](https://postimg.cc/ZCjC8jjs)

my latency: ~40ms

Sunstrider rev. 12836 (7ab2c28712b7) 2019-12-04 20:07:47 +0000

**Comment by earthworm-jim** [comment]
The addon is SEasyRotation r79987.2 if anyone else wants to try it.

**Comment by Jerrythemagicdog** [comment]
Thanks a lot, will look into it!

**Comment by earthworm-jim** [comment]
looking at these screenshots, autoshot delay seems to happen whenever it goes off outside of gcd. could've been a coincidence...

**Comment by kelno** [comment]
We fixed an issue recently where steady shot was not benefiting from haste correctly, could this be the issue here?

**Comment by earthworm-jim** [comment]
[still happening](https://i.postimg.cc/3xkZy2fx/delay.png)
this time it looks a bit different, as you can see

**Comment by kelno** [comment]
thanks

**Comment by kelno** [comment]
Okay good find!
The 0.5 cast time was reset even if the spell was queued. Fixed!
