### ISSUE TITLE
[SSC/TK] Aggro radius of mobs

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1606]
**Describe the bug**
Unsure if related to dungeons or server wide, however the aggro range of mobs seems to be too low.
Especially noticed in a raid with trash mobs that can be walked around without aggro.

**To Reproduce**
1. Enter SSC
2.  Walk around all first 3 trash packs without aggro

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
Aggro range should be larger, especially for mobs of your level or higher level such as in raids.
Anecdotal, but easily replicated.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/40563134/71825295-aa422500-30ef-11ea-922e-5a1cd5072105.png)
![image](https://user-images.githubusercontent.com/40563134/71825364-d362b580-30ef-11ea-916d-38fd81390082.png)

Rev. 13055

**Comment by kelno** [comment]
Distance is somewhat lower that other private servers but has been tweaked a lot to be blizzlike, is there any evidence that's wrong?

**Comment by omentbc** [comment]
You definitely should not be able to have your entire raid avoid multiple trash packs in SSC

**Comment by kelno** [comment]
Alright didn't see it was this bad

**Comment by kelno** [comment]
Fixed with 13068

**Comment by artieau** [comment]
Same issue still persists in rev. 13077
I can still skip the entire first few trash packs in SSC and wlak too close to most.
Needs further tweaks. @kelno

**Comment by kelno** [comment]
Reopening this one then, the general rule has been fixed but those need special handling then.

**Comment by Sheikthecatman** [comment]
Fixed as SSC and TK have been reworked since.
