### ISSUE TITLE
Magtheridon's Lair

### ISSUE THREAD

**Issue by Highdps** [SunstriderEmu/BugTracker#2363]
Hello
First cub near the entrance to lair not working correctly
Person who clicking it see that he click but it don't working, doing anything at all
Other person in raid didn't see the things from cub .
How to reproduce
Go second phase and click first cub from entrance .

It's not one situation we got this 4 times in a row with different persons clicking it ,

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next server restart!

**Comment by Highdps** [comment]
Bug still apearing on random cub. 6 or 7 wipes bcuz of that situation and it's not person fail it's something with script.
Best Regards
