### ISSUE TITLE
Quest: Karynaku

### ISSUE THREAD

**Issue by Phoelol** [SunstriderEmu/BugTracker#2408]
**Describe the bug**
I cant turn in the Quest "Karynaku" at the so called Dragon in Dragonmaw Fortress.

**To Reproduce**
Accept Quest, try to turn it in, wont work.

Quest: https://de.wowhead.com/quest=10858/karynaku#english-comments

**Expected behavior**
Should be having a yellow questionmark takin my quest. 

**Screenshots/videos**

https://gyazo.com/51cdddd548180081f422b21b41503804

**Comment by Stolemyname1** [comment]
Also having same issue. Accepted quest, cant turn in for next part.

**Comment by Sheikthecatman** [comment]
Thanks!
Should be fixed in [7d4783190c95e2309227482994bfbda77823ce70 ](https://github.com/kelno/sunstrider-scripts/commit/7d4783190c95e2309227482994bfbda77823ce70 )

**Comment by artieau** [comment]
Issue persists still.
After a period of time, the NPC  can not be interacted with by players.
Hard reset of the NPC fixes this temporarily

**Comment by Jerrythemagicdog** [comment]
Thanks, I've added some more checks to make sure she resets correctly. Live after next update.
