### ISSUE TITLE
All of my chats bugged except Guild chat 

### ISSUE THREAD

**Issue by Ozsdi** [SunstriderEmu/BugTracker#2771]
**Describe the bug**
So if i write to party or any other chat others don't see what i write i see what i write no addons in game tried from another computer too visited chat general settings all we're chechked in so it should work but it don't work maybe my account is bugged idk please help if you can 

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
The issue was resolved after a restart.

**Comment by Ozsdi** [comment]
i reinstalled the game for it and it still not works 
but from an another account it is working
