### ISSUE TITLE
All mob weapons make the 1 handed axe sound

### ISSUE THREAD

**Issue by steak-house** [SunstriderEmu/BugTracker#2821]
**Describe the bug**
When a mob attacks with an equiped weapon, their weapon always plays the one handed axe sound effect

**To Reproduce**
1. Engage in battle with a mob that has a weapon equipped other than a one-handed axe. Quilboars in the barrens, ogres in tanaris, a warlock's felguard ... Plenty of choice
2. Observe that when they attack, the noise their weapon makes is that of a one-handed axe, even if they have, say, a mace equipped.

**Expected behavior**
The impact sound effect should depend on the type of equipped weapon

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by kelno** [comment]
Fixed

**Comment by steak-house** [comment]
@kelno this is still occuring. Has the restart taken place yet ?
