### ISSUE TITLE
[Priest] Spirit of Redemption

### ISSUE THREAD

**Issue by EnterLarry** [SunstriderEmu/BugTracker#3148]
**Describe the bug**
When you die and turn into the Spirit of Redemption, aoe and cleave can still kill you as the spirit.
When this happens, you will die upon using a soulstone to ress, or re-entering the instance/raid.
Double durability damage as well as wasted soulstones.

**To Reproduce**
1. Take Spirit of Redemption Talent as priest
2. Die in a fight that doesn't end when you die, and get cleaved or aoe'd in Spirit of Redemption form. (Arcatraz Robots lightning pulses - Lurker archer multishot - SSC murloc CLs and a lot of other variations)
3. You will die in spirit form, being unable to use it to heal most of the time, and when you ress after the wipe, either by entering the raid or the dungeon again, or getting ressed or even using soulstone, you will instantly die and lose durability again, and waste time and soulstones.

**Expected behavior**
You shouldn't be able to take damage when you become the Spirit of Redemption as far as I know, but I don't have any sources to back this up.
However, you absolutely shouldn't die after ressing again.

**Comment by kelno** [comment]
Arca robot energy discharge: 38828

**Comment by kelno** [comment]
Fixed with next server update

**Comment by EnterLarry** [comment]
This is still an issue in some situations.
It just happened from Flame Quills in TK from Al'ar as well.
Sometimes it also happens if a lot of hard hitting mobs are coming for you when a raidwipe is in progress, and too many of the mobs hit you at the same time. The damage either carries over into the Spirit of Redemption, or simply doesn't change target when you turn into the Spirit in time.
