### ISSUE TITLE
[Quest] Getting down to Business

### ISSUE THREAD

**Issue by Vanill2** [SunstriderEmu/BugTracker#3182]
**Describe the bug**

Unable to complete objecte of [70] Getting down to Business  -- Netherstorm quest
Quest objective: Kill nether drakes to gather their essence
**Bug: **Even with the netherwing reputation set to 'At War' status, I'm unabel to attack the nether drakes.****

AoE attack don't work either
**After abandoning the quest I'm now unable to pick it up again, the npc is no longer availabel at the teleport platform**

**To Reproduce**

1. complete the netherwing prequest in Shadowmoonvalley
2. Find you you're not able to attack the nether drakes

Quest: https://www.wowhead.com/quest=10271/getting-down-to-business
NPC: https://www.wowhead.com/npc=18877/nether-drake

**Expected behavior**

Able to attack nether drake when reputation standard is set to at war

**Screenshots/videos**

Wowhead comments & personal experience

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Skorlaa** [comment]
I reported this BUG 23 days ago - 8. april - on this Bugtracker.

**Comment by israelfl** [comment]
Same issue today @garlander, cannot farm my Ebon Netherscales. Please FIX this bug soon!!!!!

**Comment by mdeluca0** [comment]
Still an issue. BUMP

**Comment by Marcozius** [comment]
Please Fix this.

**Comment by Morrigan83** [comment]
please fix this problem,can't farm nether dragonscales needed for set armor

**Comment by kelno** [comment]
Should be fixed now

**Comment by Orivanz** [comment]
Is there a fix for this on the user side? Still not able to attack drakes when flagged for at war.

**Comment by kelno** [comment]
What's your current rep towards the Netherwing faction?

**Comment by Orivanz** [comment]
5820/6000, I ended up buying the scales off AH.
