### ISSUE TITLE
Hunter unable to learn LOWER rank pet skills from pet trainer

### ISSUE THREAD

**Issue by PekelZoda** [SunstriderEmu/BugTracker#3560]
**Describe the bug**

I am a level 70 hunter. I know Great Stamina rank 8, 9, 10 and 11. I don't know any lower ranks of Great Stamina, and here's the bug: Pet Trainers do not show the option to teach the lower ranks to me. 

**To Reproduce**

1. Make a level 70 hunter without visiting the pet trainer even once. 
2. Visit the Pet Trainer. Train rank 8 of Great Stamina at the Pet trainer.
3. Check your "beast training" window. See how only Great Stamina rank 8 is teachable to your pets. 
4. Visit the Pet trainer again. Notice that they will not teach you Great Stamina rank 1 through 7, but only ranks 9 and above. 

**Expected behavior**

Lower ranks of pet skills should remain available for training, all through the game. 
I'd like to use my pets' excess training points somehow.

**Comment by PekelZoda** [comment]
So here's an update. The tests I made above was done at the Ironforge Pet Trainer. I later went to the Stormwind Pet Trainer, and she had the missing skill ranks available for me!

My problem is solved. Feel free to close this thread, if you deem it good. 


/PZ

**Comment by Jerrythemagicdog** [comment]
Thanks for getting back to us, still missing some data on certain trainers.

**Comment by Sheikthecatman** [comment]
Thanks! Ironforge Pet Trainer should no longer be missing the spells. The fix should be live next restart.
