### ISSUE TITLE
Paladin 2/5 T4 Healing bonus not working

### ISSUE THREAD

**Issue by Rinyt** [SunstriderEmu/BugTracker#3571]
**Describe the bug**
Additional healing is not added to Judgement of Light

**To Reproduce**
1. Cast Seal of Light
2. Cast Judgement on enemeny  target
3. Hit target with melee weapon.
4. Do it with and without t4 paladin's Justicar Raiment set on You

https://www.wowhead.com/item-set=624/justicar-raiment
Quest: https://wowhead.com?quest=
https://www.wowhead.com/spell=183778/judgment-of-light

**Expected behavior**
 After hitting target affected by Judgement of Light ,casted by paladin who have https://www.wowhead.com/item-set=624/justicar-raiment  player who hit target supose to get 115 healing instead of standard 95.

**Screenshots/videos**
![WoWScrnShot_053120_104411](https://user-images.githubusercontent.com/66199490/83348402-8ac0c880-a32c-11ea-8edd-ec5acfdd6fb8.jpg)
![WoWScrnShot_053120_104514](https://user-images.githubusercontent.com/66199490/83348405-90b6a980-a32c-11ea-974b-49fde07a6d42.jpg)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by kelno** [comment]
Fixed with next server update

**Comment by Rinyt** [comment]
After update still not working,works only for paladin who cast it,not for rest.

**Comment by kelno** [comment]
Thanks, fixed again for next server update
