### ISSUE TITLE
Cant respec

### ISSUE THREAD

**Issue by tom291990** [SunstriderEmu/BugTracker#3772]
Hi

I can't change my talents on either primary or secondary specialisation. 

I click unlearn talents and the amount for gold is blacked out see photo below.

![image](https://user-images.githubusercontent.com/62752350/85283240-ea6e4780-b484-11ea-86ba-c78d13739570.png)

When i click accept it tells me I dont have enough gold see below photo.

![image](https://user-images.githubusercontent.com/62752350/85283541-72ece800-b485-11ea-9b4f-443959ae158b.png)

I have just over 200g and have not logged on this server in a few months so i doubt it would cost a lot to respec, if anyone has any suggestions i would greatly appreciate them.

Thanks

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart!

**Comment by tom291990** [comment]
Hi when is this restart happening? its been 3 days since i've posted this ticket and i still can't respec my character 

Thanks
