### ISSUE TITLE
[paladin]CLASS quest ''True Masters of Light'' Doesn't work

### ISSUE THREAD

**Issue by kealthas06** [SunstriderEmu/BugTracker#3818]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://www.wowhead.com/quest=9737/true-masters-of-the-light
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Sheikthecatman** [comment]
This issue is already fixed (see #2669). However the server hasn't been restarted yet and the update hasn't been aplied yet.

**Comment by kealthas06** [comment]
oh thanks ive seen the fix and thats why i ve opened it caues i thought it was not fixed sorry for disturbing have a nice day :)
