### ISSUE TITLE
Ethereum Key Tablet - Alpha

### ISSUE THREAD

**Issue by Lenictavus** [SunstriderEmu/BugTracker#3909]
There is no Stasis Alpha spawned that will allow you to complete the quest 

"Stasis Chambers of Bash'ir", you can currently get the Alpha key and see the NPC in Bash'ir's landing but there is no stasis chamber alpha spawned to complete the quest.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.

**Comment by Lenictavus** [comment]
The server restarted and it is still not up, or will it be with an official update?
