### ISSUE TITLE
[Quest] An Apexis Relic

### ISSUE THREAD

**Issue by Cayman91** [SunstriderEmu/BugTracker#4160]
**Describe the bug**
Depending of the spot of the apexic relic, some colors are not clickable. I have checked 2 relics at 28,47 coords (both of the very left to the edge). The South one did not have red color clickable, the North did not have green clickable. You are supposed to click the colors which the main relic shows you to click.

**To Reproduce**

1. Activate the Apexic Relic by using Apexis Shard
2. Follow the instructions that the Relic shows you
3. Die because you cannot interact with some colors.

Item: N/A
Quest: https://db.endless.gg/?quest=11058
Spell: N/A
Object: https://db.endless.gg/?object=185890

**Expected behavior**

All 4 colors should be clickable while interacting with the item.

**Screenshots/videos**

For reference you may use any video tutorial on yt e.g. https://www.youtube.com/watch?v=h-2t1dW636k
Screenshot: https://i.postimg.cc/Cx3gjLnG/Wo-WScrn-Shot-083120-180656.jpg

**Additional context**

N/A

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.

**Comment by Cayman91** [comment]
Hey, I just wanted to test it after the changelog and few restarts and the quest still does not seem to work. Cleared cache as well.
