### ISSUE TITLE
[dungeon] brd arena script is borked

### ISSUE THREAD

**Issue by plutonium447** [SunstriderEmu/BugTracker#613]
**Current behaviour:**
bunch of missing text on the npc High Justice Grimstone when performing brd arena script
script ends early and doesnt open the doors at the end, preventing further progress into the dungeon

the first door that opens and releases mobs will work, but then it will close when all the mobs are spawned and none of the other doors will open.

![screenshot from 2019-02-15 11-12-57](https://user-images.githubusercontent.com/40911527/52829098-2538d080-3117-11e9-83d9-a2e6df774120.png)
_text is missing from the npc_

![screenshot from 2019-02-15 11-15-37](https://user-images.githubusercontent.com/40911527/52829092-22d67680-3117-11e9-9a89-a2cbdb36088f.png)
_the script ends and nothing else happens_

**Expected behaviour:**
"High" Justice Grimstone needs to lay off the kush and remember his lines like a gudboi
"
High Justice Grimstone yells: But your real punishment lies ahead.
High Justice Grimstone yells: Good riddance!
High Justice Grimstone yells: Haha! I bet you thought you were done!
High Justice Grimstone yells: The Sons of Thaurissan shall watch you perish in the Ring of the Law!
High Justice Grimstone yells: Unleash the fury and let it be done!
"
https://www.wowhead.com/npc=10096/high-justice-grimstone#comments

also the other doors need to open in sequence when the last of the mobs from the previous door die
then a boss spawns or smthng i cant remember

**Steps to reproduce the problem:**

1. .tele brd
2. run to the arena and trigger it in the middle
3. flail around for a bit until the script breaks

**rev. hash/commit:** 
Sunstrider rev. **10470** (aaf72e209219) 2019-02-13 12:14:05 +0100 (master branch) (Unix, DEBUG, Static)

edit: much presently

**Comment by plutonium447** [comment]
![screenshot from 2019-02-15 18-49-20](https://user-images.githubusercontent.com/40911527/52845277-6b5f5580-3152-11e9-9df9-bbcd02e9ab8c.png)
kek

**Comment by plutonium447** [comment]
https://youtu.be/H4D0WOS-hYY?t=307

**Comment by Sheikthecatman** [comment]
Thanks!
Fixed in [15121f2c2c521408ad7184054b5d4496ca829db1](https://github.com/kelno/sunstrider-scripts/commit/15121f2c2c521408ad7184054b5d4496ca829db1 )

**Comment by steak-house** [comment]
This is still occuring, I'm currently stuck in Ring of Law as we speak. We tried relogging, unstucking then coming back, gate was still closed.

**Comment by EL100** [comment]
confirmed. Same thing just happened to me.
